---
# It would be cleaner to only delete if k3s is the wrong version, but there isn't
# a clean way to tell the difference between the 32 bit and 64 bit version on
# Raspbian (file doesn't say anything different) so we just delete it to handle
# the case where we went from 32 to 64 bit raspbian.
- name: Delete k3s.
  file:
    path: /usr/local/bin/k3s
    state: absent

- name: Download k3s binary x64
  get_url:
      url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
#  when: ( ansible_facts.userspace_architecture == "x86_64" )
  when:
    ( ansible_facts.architecture == "x86_64" )

- name: Download k3s binary arm64
  get_url:
      url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-arm64
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
  when:
    ( ( ansible_facts.architecture is search("arm") )
        and
      ( ansible_facts.userspace_bits == "64" ) )
      or
    ( ansible_facts.architecture == "aarch64" )

- name: Download k3s binary armhf
  get_url:
      url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-armhf
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
  when:
    ( ansible_facts.architecture is search("arm") )
      and
    ( ansible_facts.userspace_bits == "32" )
