k3s_version: v1.17.4+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""

# Uncomment (and modify if necessray) the following to set the time zone set for
# all members of the cluster.
timezone: US/Pacific

# Uncomment the following to switch Raspbian RPi3 & 4 systems to 64 bit. This causes a
# new (fairly bleeding edge) 64 bit kernel to be downloaded and installed, along with
# new firmware, boot loader, etc.  There are a few benefits to doing this:
# * Slightly faster kernel performance on Raspberry Pi 4.
# * 64 bit support, allowing Raspian systems to be used in a cluster with other 64
#   bit ARM devices.
# * Abilitiy to run workloads that are only available in 64 bit and not 32 bit, e.g.
#   OpenEBS.
# Not recommended for production systems!
switch_raspian_to_64bit: true